name: GitHub Actions Main Gendiff
run-name: ${{ github.actor }} is starting GitHub Actions Main Gendiff
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm install
      - run: make lint
      - run: make test
      - uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.HEXLET_MAIN }}
        with:
          coverageCommand: make test-coverage
          debug: true